# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'S-Forum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for S-Forum

  target 'S-ForumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'S-ForumUITests' do
    # Pods for testing
  end

end
