# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'S-Forum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for S-Forum
  pod 'SDWebImage', '~> 5.0'
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'
end
